version: "3"

services:
  hono_node:
    container_name: hono_node
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./docker/src:/usr/src/app
  # MariaDB のコンテナ
  hono_mariadb:
    container_name: hono_mariadb
    image: mariadb:10.5.4
    environment:
      # ユーザー名やパスワードなどは適宜変更してください
      MYSQL_DATABASE: "saza"
      MYSQL_USER: "saza"
      MYSQL_PASSWORD: "koudai0623"
      MYSQL_ROOT_PASSWORD: "koudai0623"
    volumes:
      - ./docker/db/data:/var/lib/mysql
